# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('name', models.CharField(help_text='Enter Name', max_length=40)),
                ('reg_no', models.IntegerField(help_text='Enter your reg_no', primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Enter email', max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='Reg_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.student_info'),
        ),
    ]
